# Generated by Django 4.0.4 on 2022-05-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.TextField(max_length=250, verbose_name='Телефон')),
                ('email', models.CharField(max_length=250, verbose_name='Почта')),
                ('total_sum', models.PositiveBigIntegerField(verbose_name='Итоговая стоимость')),
                ('delivery', models.IntegerField(choices=[(1, 'Доставка по адресу'), (2, 'Самовывоз')], default=1, verbose_name='Доставка')),
                ('delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('total_price', models.PositiveBigIntegerField(verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заявка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт заявки',
                'verbose_name_plural': 'Продукты заявки',
            },
        ),
    ]
