# Generated by Django 4.0.4 on 2022-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_date_order_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
