# Generated by Django 4.0.4 on 2022-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_order_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.PositiveBigIntegerField(verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='total_price',
            field=models.PositiveBigIntegerField(verbose_name='Сумма'),
        ),
    ]
