# Generated by Django 4.0.4 on 2022-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Новая цена')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('category', models.ManyToManyField(related_name='products', to='categories.category', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
